-lオプションを追加した。
tomonariha/ruby-practices pull request #10
Opened 2022-02-04 06:28 UTC by tomonariha

LS課題４の提出用です。

2022-02-06 08:09 UTC, u1tnk requested changes

2022-02-06 08:09 UTC, u1tnk commented on 05.ls/ls.rb
> +  exit
ここでexitがあるのはなぜでしょう？

2022-02-06 08:09 UTC, u1tnk commented on 05.ls/ls.rb
> +  @total_blocks = []
インスタンス変数を使ってメソッド内外とのデータのやり取りをするのはデータの流れが分かりづらくなるのであまり良くないです。

例えば

```
{
  total_blocks: ...,
...
}
```

みたいにhashを使えばひとまとめで渡せます。

2022-02-06 08:09 UTC, u1tnk commented on 05.ls/ls.rb
> +  file_type = { 'file' => '-', 'directory' => 'd',
ちょっと細かい話ですが、
一行でおさまらないときに複数行にするのは良いのですが、複数行にするのであれば各行は一つずつにしましょう。
見やすいのと、編集しやすいというのが理由です。

2022-02-06 08:09 UTC, u1tnk commented on 05.ls/ls.rb
> -    Dir.glob('*', File::FNM_DOTMATCH) { |f| @list << f }
ここは `-l`オプションとは関係無いように思いますが、どうでしょうか？

2022-02-06 14:43 UTC, tomonariha commented on 05.ls/ls.rb
> +  exit
ifを後に置く書き方を使っていたため、lオプションのリストが表示された後、通常のリストが表示されてしまうのでexitで止めていました。
ifの分岐の仕方を変えて、exitを使わないようにしました。[544a96b](https://github.com/tomonariha/ruby-practices/pull/10/commits/544a96b8feeb4365b8d1acf4c0b4a9fa3baedb3c)

2022-02-06 14:46 UTC, tomonariha commented on 05.ls/ls.rb
> +  @total_blocks = []
勉強になります！
ハッシュで引数を渡す方法を使ってインスタンス変数を使わないようにしました。[e425f2c](https://github.com/tomonariha/ruby-practices/pull/10/commits/e425f2c818eb57f07fa3134ce137294f50e50350)

2022-02-06 14:51 UTC, tomonariha commented on 05.ls/ls.rb
> +  file_type = { 'file' => '-', 'directory' => 'd',
各行一つずつに修正しました。[8ee55cb](https://github.com/tomonariha/ruby-practices/pull/10/commits/8ee55cbfcf8e69ab70ee3ef4fe72f0626a4c8eeb)
確かにこの方が見やすい・編集しやすいですね。

2022-02-06 14:56 UTC, tomonariha commented on 05.ls/ls.rb
> -    Dir.glob('*', File::FNM_DOTMATCH) { |f| @list << f }
すみません、また関係ないところに手をつけていました。
今更ですが、関係ないオプションは消しておいても良かったかと思います。

2022-02-08 12:05 UTC, u1tnk requested changes

2022-02-08 12:05 UTC, u1tnk commented on 05.ls/ls.rb
> +  file_type = { 'file' => '-',
すみません、指摘漏れていて、rubocopでひっかかったで気づいたのですが、これは定数にした方が良いですね。

定数にして、メソッドの直前に定義すれば大丈夫です。
また、 複数データが入っているので FILE_TYPESのように複数形の方が一般的です。

2022-02-08 12:05 UTC, u1tnk commented on 05.ls/ls.rb
> +parse_options
これだと「メイン処理はオプションをparseするだけなのか？？？」ってなっちゃうし、それぞれの処理の独立性を高めるためにもバラした方が良いですね。

一部書いちゃうとこんな感じです。

```
options = parse_options
list = generate_list(options)
....
```
という感じです。

これも最初からで今さら申し訳無いです 🙏

2022-02-08 15:01 UTC, tomonariha commented on 05.ls/ls.rb
> +  file_type = { 'file' => '-',
回答ありがとうございます！
ハッシュ部分を定数にして外に出しました。[8336db5](https://github.com/tomonariha/ruby-practices/pull/10/commits/8336db567009da3c9ed71a41626071b5345b2d70)

2022-02-08 15:04 UTC, tomonariha commented on 05.ls/ls.rb
> +parse_options
なるほど、参考になります！
入れ子にしていたメソッド呼び出し部分をまとめて、新たにmainメソッドを作ってみました。
すみません、rubocop対応の部分と混ざってしまい、少し見辛いかもです。[2f54415](https://github.com/tomonariha/ruby-practices/pull/10/commits/2f54415ef7b675e7f2f7103b2eff89f7ed9b84bc)

2022-02-09 01:54 UTC, u1tnk approved these changes

2022-02-09 01:54 UTC, u1tnk commented on 05.ls/ls.rb
> +               'unknown' => 'u' }.freeze
余談ですが、もちろんfreezeは付けて問題無いのですが、個人的には無し派です。メリットは小さいので見やすい、書きやすい方が好きなので。
これは 宗派的なもので現場によって違うと思うので現場の流儀に合わせれば良いです 🙆‍♀️

2022-02-09 01:54 UTC, u1tnk commented on 05.ls/ls.rb
> +def main
mainにまとめて分かりやすくなりましたね 👍

2022-02-09 07:19 UTC, tomonariha commented on 05.ls/ls.rb
> +def main
ありがとうございます！

2022-02-09 07:20 UTC, tomonariha commented on 05.ls/ls.rb
> +               'unknown' => 'u' }.freeze
なるほど！現場によって違うのですね。
今回のfreezeはrubocopに指摘されたので付けました😅

2022-02-10 02:54 UTC, merged